.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xcbc_qt test_xcbc_qt
clean: FORCE
	$(MAKE) -C .. xcbc_qt_clean test_xcbc_qt_clean
check: FORCE
	$(MAKE) -C .. test_xcbc_qt_check
xcbc-qt xcbc-qt.exe: FORCE
	 $(MAKE) -C .. xcbc_qt
apk: FORCE
	$(MAKE) -C .. xcbc_qt_apk
